### PR TITLE
modify readme file

### PR DESCRIPTION
**Pull request by louicoder**
### What does this PR do?
- Adds description of the project future
- Adds authors and collaborators of the project

### Any more information to look out for when testing this PR
- N/A

### CODE REVIEW

**Comment by Anekenonso** [comment]
this looks good for now!

**Review by Anekenonso — CHANGES_REQUESTED** [review]
maybe webscrapper can be used to scrap pieces of information from other website/web-app for marketing purpose

**Comment by louicoder** [comment]
Cool, lemme change that to something more meaningful. Thanks @Anekenonso

**Comment by louicoder** [comment]
> maybe webscrapper can be used to scrap pieces of information from other website/web-app for marketing purpose

Finished implementing the requested changes, please check and see if it's better. @Anekenonso

**Review by Anekenonso — DISMISSED** [review]
looks better for now!.

**Review by Anekenonso — APPROVED** [review]

**Pull request merged**
