### PR TITLE
Whatsapp integration

### PR DESCRIPTION
**Pull request by louicoder**
#### What does this PR do?
- implements whatsapp messaging in the application. messages can be sent to a number or numbers. This can be configured in the **whatsapp.js** file.

#### Any more information to look out for when testing this PR
- add numbers to the numbers array in the **whatsapp.js** file
- add the whatsapp sandbox number to your contacts. The number is **+1 415 523 8886**
- send a message saying **join managed-busy** to activate the sandbox and should get a message welcoming you to the sandbox.
- In package.json change start script **"start":"nodemon server.js"** to **`"start":"nodemon whatsapp.js"`**
- run command **`npm start`** and you should get a whatsapp mesage from `+14155238886`

### CODE REVIEW

**Comment by louicoder** [comment]
@Anekenonso please review this PR so it can be merged. Thanks alot :nerd_face:

**Review by Anekenonso — APPROVED** [review]
green light!

**Comment by Anekenonso** [comment]
after fetching the develop brant **whatsapp.js** wasn't there

**Comment by louiCoder** [comment]
> green light!

@Anekenonso , you should then try to do a `git fetch --all`. Let me know if you still get the same issue. :wink:

**Comment by louicoder** [comment]
> after fetching the develop brant **whatsapp.js** wasn't there

@Anekenonso , you should check out the branch on this PR since the PR is not yet merged to develop, so you cannot find this file there :wink:

**Comment by louicoder** [comment]
connects #18

**Pull request merged**
